src/components/HomeBulkSend/HomeHeader.vue, src/layouts/BulkSend/BulkSendHomeLayout.vue, src/views/BulkSend/HomeBulkSend.vue
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Just base home components and view to give a proper structure to the project
Added base header component, layout and view for the home page
=> Feat: base home view

src/components/BasicDivider.vue, src/layouts/BulkSend/BulkSendHomeLayout.vue
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
A divider is a simple line that separates the content, this component was created to avoid the duplication of CSS code that could happen in every view that has a divider 
Created a basic divider component
=> Add BasicDivider component

src/__tests__/components/HomeBulkSend/RecentSends.spec.ts, src/__tests__/utils/date.spec.ts, src/__tests__/views/BulkSend/HomeBulkSend.spec.ts, src/components/HomeBulkSend/RecentSends.vue, src/constants/recentSends.ts, src/locales/en.json, src/locales/es.json, src/locales/pt_br.json, src/types/recentSends.ts, src/utils/date.ts, src/views/BulkSend/HomeBulkSend.vue
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Base component to view recent sends 
Refactored HomeBulkSend to be more concise, using the new RecentSends component
- [Design File 1](https://www.figma.com/design/oYQwtQhHR0YMbug78GbR3g/Bulk-send?node-id=113-1516&m=dev)
=> Feat: recent sends base component

src/__tests__/components/HomeBulkSend/SendElementInfo.spec.ts, src/components/HomeBulkSend/RecentSends.vue, src/components/HomeBulkSend/SendElementInfo.vue, src/components/MetricsTable.vue, src/locales/en.json, src/locales/es.json, src/locales/pt_br.json, src/types/recentSends.ts
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Component to display information about recent sends
Added the new component and unit tests for the rendering data
- [Design File 1](https://www.figma.com/design/oYQwtQhHR0YMbug78GbR3g/Bulk-send?node-id=148-2228&m=dev)
In the design, the `Ended on` label is not bold, but i've talked with our designer and we agreed that it should be bold. The design file will be updated in the future.
=> Feat: SendElementInfo

docker/Dockerfile
* * [X] Bugfix
* * [ ] Tests
* * [ ] Other
Build requires node >= v22.18
Updated dockerfile node version
=> chore: update Node.js version to 22.18.0 in Dockerfile

src/__tests__/api/channels.spec.ts, src/__tests__/setup/global-mocks.ts, src/__tests__/stores/project.spec.ts, src/__tests__/views/BulkSend/HomeBulkSend.spec.ts, src/api/resources/channels.ts, src/stores/project.ts, src/types/channel.ts, src/types/recentSends.ts, src/views/BulkSend/HomeBulkSend.vue, vitest.config.ts
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
MMlite disclaimer should only be displayed if the project has a WAC channel but does not have an active MMLite configuration
Added api integration to fetch project channels and check if MMlite disclaimer should be displayed
=> Feat: mmlite api integration

.github/workflows/build-bulksend-webapp-push-tag-shared.yaml
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
- Resolve o erro "ERROR: invalid key-value pair "": empty key" que ocorria durante o build da imagem Docker.
- O problema era causado pela passagem de um argumento de build vazio (`--build-arg  `) para o comando `docker buildx build`, que não é uma sintaxe válida.
- A correção garante que todos os argumentos de build sejam corretamente formatados antes de serem passados para o comando Docker, prevenindo a falha do pipeline de CI/CD.
- [Design File 1](link_to_design_file_1)
=> Corrige erro de build devido a argumento vazio

eslint.config.ts, src/__tests__/api/broadcasts.spec.ts, src/__tests__/stores/broadcasts.spec.ts, src/api/resources/broadcasts.ts, src/constants/broadcasts.ts, src/constants/recentSends.ts, src/stores/broadcasts.ts, src/types/broadcast.ts, src/types/requests.ts, src/utils/enum.ts
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Broadcasts Store will replace the current RecentSends naming, this PR aims to add the required files for the future refactor
Added broadcasts store and API calls, with their related types and tests
Updated ESLint config to us Typescript no-unused-vars rule
=> Feat: broadcasts API and store

src/__tests__/components/HomeBulkSend/RecentSends.spec.ts, src/__tests__/components/HomeBulkSend/RecentSendsList.spec.ts, src/__tests__/components/HomeBulkSend/SendElement.spec.ts, src/__tests__/components/HomeBulkSend/SendElementInfo.spec.ts, src/__tests__/components/modals/NewContactGroup.spec.ts, src/__tests__/utils/factories.ts, src/components/HomeBulkSend/RecentSends.vue, src/components/HomeBulkSend/RecentSendsList.vue, src/components/HomeBulkSend/SendElement.vue, src/components/HomeBulkSend/SendElementInfo.vue, src/components/modals/NewContactGroup.vue, src/locales/en.json, src/locales/es.json, src/locales/pt_br.json, src/types/recentSends.ts
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Fetch recent sends data from API
Updated the component to fetch and render data according to the API response
=> feat: recents sends data from API

src/App.vue, src/layouts/BaseLayout.vue, src/layouts/BulkSend/BulkSendHomeLayout.vue, src/layouts/BulkSend/NewBroadcastLayout.vue
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Reutilize base layout component with shared styles between pages layouts
Refactores existing layouts with new BaseLayout
=> Feat: base layout

src/locales/en.json, src/locales/es.json, src/locales/pt_br.json
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Upcoming translations for new broadcasts components
Added translations
=> Feat: new broadcast translations

src/constants/broadcasts.ts, src/stores/broadcasts.ts, src/types/broadcast.ts
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Store used to manage the new broadcast flow state
Added store management
=> feat: NewBroadcastPage store

src/App.vue, src/main.ts, src/utils/storage.ts
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Use moduleStorage to avoid conflicts between modules
Added module storage and updated usage
=> Feat: module storage

src/locales/en.json, src/locales/es.json, src/locales/pt_br.json
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Added PT_BR, EN and ES translations for contact import and template
=> feat: contact import and templates localization updates

tsconfig.app.json, tsconfig.json, tsconfig.vitest.json
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Methods like replaceAll are only available in >=ES2021, since current browsers are all compatible with ES2021 we can update it [ref](https://caniuse.com/?feats=mdn-javascript_builtins_string_replaceall,mdn-javascript_builtins_promise_any,mdn-javascript_builtins_weakref,mdn-javascript_operators_logical_or_assignment,mdn-javascript_operators_logical_and_assignment,mdn-javascript_operators_nullish_coalescing_assignment,mdn-javascript_grammar_numeric_separators,mdn-javascript_builtins_finalizationregistry)
Updated TS target
=> Feat: update ts target

src/views/BulkSend/HomeBulkSend.vue
* * [X] Bugfix
* * [ ] Tests
* * [ ] Other
`generalPerformanceData` need to be reactive since it uses store values
Updated `generalPerformanceData` to be a computed property
=> Fix: general performance initial load

src/__tests__/components/NewBroadcast/ContactImport/ContactImportUpload.spec.ts, src/components/NewBroadcast/ContactImport/ContactImportUpload.vue
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Upload component to handle new import files
- [Design File 1](https://www.figma.com/design/oYQwtQhHR0YMbug78GbR3g/Bulk-send?node-id=113-3009&m=dev)
=> Feat: contact import upload

src/__tests__/components/NewBroadcast/ContactImport/ContactImportProcessingOverview.spec.ts, src/components/NewBroadcast/ContactImport/ContactImportProcessingOverview.vue
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Display current fileand contact count of an import
- [Design File 1](https://www.figma.com/design/oYQwtQhHR0YMbug78GbR3g/Bulk-send?node-id=113-3464&m=dev)
=> Feat: contact import processing overview

src/__tests__/components/NewBroadcast/ContactImport/ContactImportProcessingForm.spec.ts, src/components/NewBroadcast/ContactImport/ContactImportProcessingForm.vue
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Form to fill group name or select a grou, or even no group at all
- [Design File 1](https://www.figma.com/design/oYQwtQhHR0YMbug78GbR3g/Bulk-send?node-id=128-2689&m=dev)
=> Feat: contact import processing form

src/__tests__/components/NewBroadcast/ContactImport/ContactImport.spec.ts, src/__tests__/components/NewBroadcast/ContactImport/ContactImportProcessing.spec.ts, src/components/NewBroadcast/ContactImport/ContactImport.vue, src/components/NewBroadcast/ContactImport/ContactImportProcessing.vue
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Added Upload to ContactImport
- [Design File 1](https://www.figma.com/design/oYQwtQhHR0YMbug78GbR3g/Bulk-send?node-id=113-2994&m=dev)
=> Feat: integrate contact import upload

src/layouts/BaseLayout.vue
* * [X] Bugfix
* * [ ] Tests
* * [ ] Other
Added scroll to app, to avoid overflow in parent application 
Added overflow to base layout
=> Fix: base layout scroll

src/locales/en.json, src/locales/es.json, src/locales/pt_br.json
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Added translations for template selection page
Added EN, ES and PT translations
=> feat: add template selection translations

src/__tests__/stores/broadcasts.spec.ts, src/__tests__/stores/templates.spec.ts, src/api/resources/templates.ts, src/stores/broadcasts.ts, src/stores/templates.ts, src/types/broadcast.ts
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Store and API for templates
Added store and API for templates with tests
Updated NewBroadcastState to have the current selected template
=> Feat: templates store and api

src/__tests__/components/NewBroadcast/TemplateSelection/TemplateSelection.spec.ts, src/components/NewBroadcast/TemplateSelection/TemplateSelection.vue
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Displaying filters, list and preview
- [Design File 1](https://www.figma.com/design/oYQwtQhHR0YMbug78GbR3g/Bulk-send?node-id=113-4822&m=dev)
=> Feat: template selection

src/__tests__/views/BulkSend/NewBroadcast.spec.ts, src/views/BulkSend/NewBroadcast.vue
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Integrate template selection into NewBroadcast flow
Updated component and tests
Obs: a refactor will be implemented in the near future for the NewBroadcast component to avoid overwhelming logic for page and continue button management
- [Design File 1](https://www.figma.com/design/oYQwtQhHR0YMbug78GbR3g/Bulk-send?node-id=113-4775&m=dev)
=> Feat: new broadcast with template selection

src/__tests__/components/NewBroadcast/TemplateSelection/TemplateSelection.spec.ts, src/__tests__/components/NewBroadcast/TemplateSelection/TemplateSelectionList.spec.ts, src/__tests__/views/BulkSend/NewBroadcast.spec.ts, src/api/resources/templates.ts
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Top level import was causing issues in test files since pinia was being called early
Removed toplevel import of project store and adjustes tests to remove no longer needed mocks
=> refactor: remove top level project store import

src/__tests__/components/NewBroadcast/GroupSelection/GroupSelectionListOption.spec.ts, src/components/NewBroadcast/GroupSelection/GroupSelectionListOption.vue
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
GroupOption should allow click on root section instead of just the checkbox 
Moved clik handling into root section
=> Feat: group option select on click

src/__tests__/api/projects.spec.ts, src/__tests__/stores/project.spec.ts, src/api/resources/projects.ts, src/constants/project.ts, src/stores/project.ts, src/types/project.ts
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Project info to know if the project has brainOn enabled
Updated store and API, with tests
=> Feat: project info

src/locales/en.json, src/locales/es.json, src/locales/pt_br.json
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Select variables and review & send translations
Added translations
=> Feat: variables and review translations

src/__tests__/components/NewBroadcast/VariablesSelection/VariablesSelectionOverview.spec.ts, src/components/NewBroadcast/VariablesSelection/VariablesSelectionOverview.vue
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Simple component to display variable selection mapping
- [Design File 1](https://www.figma.com/design/oYQwtQhHR0YMbug78GbR3g/Bulk-send?node-id=227-6794&m=dev)
- [Design File 2](https://www.figma.com/design/oYQwtQhHR0YMbug78GbR3g/Bulk-send?node-id=227-6440&m=dev)
=> feat: add VariablesSelectionOverview component 

src/__tests__/components/NewBroadcast/ConfirmAndSend/ConfirmAndSendAudience.spec.ts, src/components/NewBroadcast/ConfirmAndSend/ConfirmAndSendAudience.vue
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Simple component to display new broadcast info
- [Design File 1](https://www.figma.com/design/oYQwtQhHR0YMbug78GbR3g/Bulk-send?node-id=227-6431&m=dev)
=> Feat: confirm and send audience

src/__tests__/components/NewBroadcast/ConfirmAndSend/ConfirmAndSend.spec.ts, src/__tests__/components/NewBroadcast/ContactImport/ContactImportProcessing.spec.ts, src/__tests__/stores/contactImport.spec.ts, src/components/NewBroadcast/ConfirmAndSend/ConfirmAndSend.vue, src/components/NewBroadcast/ContactImport/ContactImportProcessing.vue, src/stores/contactImport.ts, src/types/contactImport.ts
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Get download url from backend and allow user to download on click
=> Feat: contact import duplicate download

src/__tests__/components/NewBroadcast/ContactImport/ContactImportProcessingForm.spec.ts, src/components/NewBroadcast/ContactImport/ContactImportProcessingForm.vue
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
No longer supporting imports without a group specified
Removed import without group option
=> Fix: remove import without group

src/__tests__/components/modals/NewContactGroup.spec.ts, src/components/modals/NewContactGroup.vue, src/locales/en.json, src/locales/es.json, src/locales/pt_br.json
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Alert user if success/error on group creation
Added unnnic alert and tests
- [Design File 1](link_to_design_file_1)
=> feat: NewContactGroup action status notification

src/__tests__/components/NewBroadcast/ConfirmAndSend/ConfirmAndSend.spec.ts, src/__tests__/components/NewBroadcast/VariablesSelection/VariablesSelection.spec.ts, src/components/NewBroadcast/ConfirmAndSend/ConfirmAndSend.vue, src/components/NewBroadcast/VariablesSelection/VariablesSelection.vue, src/constants/broadcasts.ts, src/locales/en.json, src/locales/es.json, src/locales/pt_br.json, src/types/contacts.ts
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Users should be able to select the contact name as a variable, but the contact name is not a custom field, and all contacts have by default
Manually added ad handled contact name selection, added tests
=> Feat: contact name as field

src/components/NewBroadcast/ConfirmAndSend/ConfirmAndSendAudience.vue
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
As suggested in #117 
Refactored to use a map instead of switch
=> Refactor: confirm and send audience cost map

src/__tests__/components/NewBroadcast/ConfirmAndSend/ConfirmAndSend.spec.ts, src/__tests__/stores/broadcasts.spec.ts, src/api/resources/broadcasts.ts, src/components/NewBroadcast/ConfirmAndSend/ConfirmAndSend.vue, src/locales/en.json, src/locales/es.json, src/locales/pt_br.json, src/stores/broadcasts.ts, src/types/broadcast.ts
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Added flow in broadcast creation
=> Enhance broadcast creation by adding flow reference 

src/components/NewBroadcast/ContactImport/ContactImportProcessing.vue, src/types/contactImport.ts
* * [X] Bugfix
* * [ ] Tests
* * [ ] Other
Duplicates can be a null value
Prevented error
=> Fix: duplicates count

src/views/BulkSend/HomeBulkSend.vue
* * [X] Bugfix
* * [ ] Tests
* * [ ] Other
Missing percentage sign
Added percentage sign
=> fix: update success rate display in HomeBulkSend component

src/locales/en.json, src/locales/es.json, src/locales/pt_br.json
* * [X] Bugfix
* * [ ] Tests
* * [ ] Other
Home title was updated
=> fix: update home title

src/__tests__/components/NewBroadcast/GroupSelection/GroupSelectionOverview.spec.ts, src/components/NewBroadcast/GroupSelection/GroupSelectionOverview.vue
* * [X] Bugfix
* * [ ] Tests
* * [ ] Other
Ensure only 2 decimals are displayed
=> fix: format cost value in GroupSelectionOverview 

src/__tests__/components/NewBroadcast/TemplateSelection/TemplateSelectionPreview.spec.ts, src/__tests__/components/NewBroadcast/VariablesSelection/VariablesSelection.spec.ts, src/components/NewBroadcast/ConfirmAndSend/ConfirmAndSend.vue, src/components/NewBroadcast/TemplateSelection/TemplateSelectionPreview.vue, src/components/NewBroadcast/VariablesSelection/VariablesSelection.vue
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Allow variable previw in confirm and send step
Refactor to replace variables from within TemplatePreview component
=> feat: enhance TemplateSelectionPreview variable replacement
